### ISSUE TITLE
4.3 (2 bis)

### ISSUE THREAD

**Issue by CorradoLanera** [Tazinho/Advanced-R-Solutions#210]
I have interpreted the question as the answer should be

```
start <- sample(nrow(iris) - m, 1)
end   <- start + m

iris[sample(start:end), , drop = FALSE]
```

**Comment by henningsway** [comment]
If we interpret a "contiguous" sample as a *blocked sample*, then the current solution looks good to me:

- we do not resample the selected rows, because the sampel is "blocked"
- we add/substract 1 to start/end because we want the last m rows to be able to be selected as well. (in the case of m = 10, we want row 141:150 as the last possible block)

Do you agree? :)

Thank you for raising these issues!

**Comment by henningsway** [comment]
Please reopen, if necessary. :)

**Comment by CorradoLanera** [comment]
Totaly agree to consider the first option as valid. Could it be useful to purpose a solution for both the interpretations?

Regarding the second point, I totally agree too, I made a really stupid mistake 😂

PS: sorry for the late answer.
