### ISSUE TITLE
Find out why hash tags appear as tool tips over headlines

### ISSUE THREAD

**Issue by Tazinho** [Tazinho/Advanced-R-Solutions#234]
When scrolling over headlines in the online version my browser (firefox) displays one hash tag after each headline as a tool tip. As this is some really weird new behaviour which also doesn't appear in other bookdown books, e.g. Adv R or Tidy Text Mining, I believe we should investigate which of our settings caused these changes and resolve this.

**Comment by henningsway** [comment]
The purpose of these hashtags is to provide a convenient way to link to a section rather than a chapter. When you click on it you see that the browser "jumps" to the headline and the url in the browser changes slightly (# + headername is added).

I think this is generally a nice feature, which the tidy textmining book also uses, though the use another new bookdown-theme and have a link icon behind each heading (which seems to make a lot of sense).

Let's see, if we want to change this behaviour and we can also consider updating the theme.

**Comment by Tazinho** [comment]
I thought it is explained here,
https://blog.rstudio.com/2020/12/21/rmd-news/

the anchor section. Not sure, though.

**Comment by henningsway** [comment]
Yes, I think it is! :)
