### ISSUE TITLE
Create overview of unsolved exercises 

### ISSUE THREAD

**Issue by henningsway** [Tazinho/Advanced-R-Solutions#73]
Let's see what we still have to do content-wise.

Malte will create and commit an Rmd-file, which contains unsolved exercises. When new exercises should come up in the 2nd Ed. we will also add them here.

**Comment by henningsway** [comment]
Just another idea for structuring this, still WIP:

# I Foundations
## 2. Data structures
### [Object Size](https://bookdown.org/Tazinho/Advanced-R-Solutions/names-and-values.html#object-size)
- [ ] Exercise 2
    - unanswered 

### [Modify in Place](https://bookdown.org/Tazinho/Advanced-R-Solutions/names-and-values.html#modify-in-place)

- [ ] Exercise 1
    - needs to be revised (+ some details maybe)
    - pulled by @henningsway on 2018-10-06

## 3. Subsetting
## 4. Functions

**Comment by Tazinho** [comment]
The problem with both is that our source (Hadley`s book) is not static. So we cannot use numbers to track things which require some time.

**Comment by henningsway** [comment]
Yes.

When we go down to the question-block (3rd level) the questions numbers are less likely to change than when we rely on the numbers entirely.

Maybe we could add have a mini description for an exercise capturing the gist of the question? (see edit above)

**Comment by Tazinho** [comment]
The problem is really that everything can change. New chapters, chapter renamings, subsection renamings, completely new exercises, different order of exercises or movement of exercises into different blocks, small additions to exercises which add a complete part and sometimes just reformulations. Therefore a short description won't be enough to track everything consistently in the long run.

One possible solution, would be to add a filter to the book to switch between solved and open exercises.

**Comment by henningsway** [comment]
I would favour a github-based result, because we can tag each other, discuss etc easily.

Maybe we can do a test run on the first two parts: Foundations and Functional Programming
(based on https://github.com/Tazinho/Advanced-R-Solutions/issues/37#issuecomment-427576896)

What would meet your needs @robertzk @peterhurford ?

**Comment by Tazinho** [comment]
Ok, lets see how this looks. As description I will use the number and the first line of the question.

# I Foundations

## [Names and values](https://bookdown.org/Tazinho/Advanced-R-Solutions/names-and-values.html)

### [Object Size](https://bookdown.org/Tazinho/Advanced-R-Solutions/names-and-values.html#object-size)
- [ ] 1. In the following example, why are object.size(y) and obj_size(y) so radically different? ...
- [ ] 2. Take the following list. Why is its size somewhat misleading? ...

### [Modify-in-place](https://bookdown.org/Tazinho/Advanced-R-Solutions/names-and-values.html#modify-in-place)
- [ ] 1. Wrap the two methods for subtracting medians into two functions, then use the bench package to ...
- [ ] 2. What happens if you attempt to use tracemem() on an environment?

## [Vectors](https://bookdown.org/Tazinho/Advanced-R-Solutions/vectors.html)

### [Atomic vectors](https://bookdown.org/Tazinho/Advanced-R-Solutions/vectors.html#Atomic-vectors)
- [ ] 1. How do you create scalars of type raw and complex? (See ?raw and ?complex)
- [ ] 5. Precisely what do is.atomic(), is.numeric(), and is.vector() test for?

### [Attributes](https://bookdown.org/Tazinho/Advanced-R-Solutions/vectors.html#Attributes)
- [ ] 1. How is setNames() implemented? How is unname() implemented? Read the source code.
- [ ] 2. What does dim() return when applied to a 1d vector? When might you use NROW() or NCOL()?

### [S3 atomic vectors](https://bookdown.org/Tazinho/Advanced-R-Solutions/vectors.html#S3-atomic-vectors)
- [ ] 1. What sort of object does table() return? What is its type? What attributes does it have? How ...

### [Lists](https://bookdown.org/Tazinho/Advanced-R-Solutions/vectors.html#Lists)
- [ ] 1. List all the ways that a list differs from an atomic vector. 
- [ ] 3. Compare and contrast c() and unlist() when combining a date and date-time into a single vector.

### [Data frames and tibbles](https://bookdown.org/Tazinho/Advanced-R-Solutions/vectors.html#Data-frames-and-tibbles)
- [ ] 2. What happens if you attempt to set rownames that are not unique?
- [ ] 3. If df is a data frame, what can you say about t(df), and t(t(df))? Perform some ...

**Comment by henningsway** [comment]
I created 3 Tickets for the first 3 open chapters. The next chapters will be tackled afterwards.

Will close this for now, as there is no current todo. (may reopen after first three chapters are done)
