### ISSUE TITLE
[Edit] "Names and Values"-Chapter

### ISSUE THREAD

**Issue by henningsway** [Tazinho/Advanced-R-Solutions#78]
Let's eventually try to finish one chapter to see, what kind of result we are aiming for and what steps are needed to get there.

We can do this, once the 90% milestone is reached.

## TO DO
- [x] Modify-in-place -> 1. Explain why the following code doesn’t create a circular list...
- [x] improve first exercise of copy-on-modify
- [x] double check graphic (remove x)
- [x] check if 2nd exercise of object size can be improved
    - comment: don't think I can improve here.
    - [x] @Tazinho why is there a code chunk as well as inline-code in this answer?
    - __Edit__: I think it might be nice to give the answer in a sentence (inline code), but also provide the code on how to get there for the reader.
- [x] check 3rd object-size exercise some time
    - not us right now :)
    - observe https://github.com/hadley/adv-r/issues/1324
- [x] fix graphic for last exercise (median subtraction)
- [x] @henningsway read once through the chapter
- [x] @henningsway review the final exercise (3rd object size ["predicition of object sizes"])

**Comment by Tazinho** [comment]
I think [names and values](https://advanced-r-solutions.rbind.io/names-and-values.html) is more or less ready. I already reviewed and edited the first half. Can you also review this one? Afterwards I would suggest that this is the first one that we should give und "official review" ;-)

**Comment by henningsway** [comment]
Will do!

**Comment by Tazinho** [comment]
Potential critique points (some are more relevant some less. With everything else I am already quite happy)

## 1

I am not too happy with the formulations in the first one of Copy-on-modify

Q: Why is tracemem(1:10) not useful?

A: Without a binding 1:10 will not stay in memory (there will be no reference) and it makes no sense to track an object for copies which doesn’t exist. Also when we assign 1:10 to a name, it will be clear, that 1:10 will only be the value of the object created and there is no “general” object 1:10, which one would wan’t to track.

## 2

In grafic in the last (4th) exercise of copy-on-modify the old **X** with the pointed borders might be unnecessary. I think it's already super clear without it and it might confuse a bit in the first moment

![grafik](https://user-images.githubusercontent.com/11295192/49102928-5f15db80-f27a-11e8-81d7-20c92fbf0192.png)

## 3

In the 2nd of "Object size" I am also not sure, but we already made an issue and this is what I came up with after Hadleys hint ...

Q: Take the following list. Why is its size somewhat misleading?

```r
x <- list(mean, sd, var)
# obj_size(x)
#> 16,928 B
```

A: It is somewhat misleading, because all three functions are built-in to R as part of the base and stats packages and hence always loaded.

Via the following calculations we can see that this holds for about 2696 objects which are usually loaded by default and use about 50.93 MB:

`some R code`

## 4

This one probably needs to be updated from our side

Q: Predict the output of the following code:

x <- 1:1e6
obj_size(x)

y <- list(x, x)
obj_size(y)
obj_size(x, y)

y[[1]][[1]] <- 10
obj_size(y)
obj_size(x, y)

y[[2]][[1]] <- 10
obj_size(y)
obj_size(x, y)

A: Since lobstr::obj_size() currently throws returns very different values, we will use unclass(pryr::obj_size()) for now.

## 5

This one I need to review

Q: Wrap the two methods for subtracting medians into two functions, then use the bench package to carefully compare their speeds. How does performance change as the number of columns increase?

A: First, let’s define a function to create some random data and a function to subtract the median from each column. ...

**Comment by Tazinho** [comment]
Trying to summarise the process to finish one chapter and overgive it to Hadley. 

1. We get the signal from Hadley that the chapter (more important the exercises in the chapter) are fixed.
2. One of @henningsway and @Tazinho goes through the whole chapter and does the following steps
  - Sync the text and the order of all exercises in the chapter between Adv R and Adv R Solutions.
  - Read through all exercises. Edit them if possible and mark their correct status in green (think this solution is correct), orange (this solution is definitely not correct or sth. is missing. If sth. is missing, try to includede a todo). 
3. Report all open exercises to the other one (@henningsway or @Tazinho) maybe the other one can solve the exercise or has a more specific question to raise in an issue to Hadley. 
4. When it seems that we are out of thoughts (this can include that some exercises are still open), we run a final spellcheck.
5.  Afterwards we give the chapter over to Hadley. Therefore we create an issue names "Reviwe (ch. xx) <"Name of chapter>" where we link all exercise sections and checkmark all exercises so that Hadley can easily mark wchich exercises are "ok".
6. If an exercise is ok, we don't touch it anymore until we get the final editing requirements form Ch. & H. (Of course we can edit clear mistakes...)

**Comment by Tazinho** [comment]
I reviewed the last of the 5 exercises. However, there is an issue: in the benchmark for 1500 columns, it is not visible that `subtract_medians` has linear computational costs. It would help to run this benchmark with 2000 or more columns. However, this doesn't seem to work with the continuous integration :(
Have an idea how to fix it? Maybe add it as a png instead?

**Comment by henningsway** [comment]
jip, let's think about this. For longer benchmark we are running into a timeout on travis.

**Comment by Tazinho** [comment]
Strange. I tried `max_iterations = 50L` and also I checked the size of a corresponding data frame which shouldn't be too heavy with 160 MB...

```r
bla <- as.data.frame(matrix(rnorm(10000 * 2000), ncol = 2000))
dim(bla)
#> [1] 10000  2000
pryr::object_size(bla)
#> 160 MB
```

**Comment by henningsway** [comment]
it just takes too long to compute on the (small) machine. I'll workaround it in a little bit. :)

**Comment by henningsway** [comment]
I'm at it.

I think, we should think if we can structure the editing and QA-process more clearly.
This issue quickly blew up and we'll have to do this for each chapter. :)

**Comment by henningsway** [comment]
I will rewrite 1) from above later.

@Tazinho regarding 4) and lobstr vs pryr - what would be the correct answer for now? It should be easy to replace lobstr with pryr, but I am not entirely sure, how to best approach this.

**Comment by Tazinho** [comment]
TBH I would like to keep 4) open for several reasons. Mainly I think this is an issue in Advanced R (it is also still open there). It is not clear how Hadley will solve it. He might throw this exercise out, he might introduce altrep, ... I don't know. So this exercise can be treated in the same way as everything else which is not finished in Advanced R. Don't touch ;-)

**Comment by henningsway** [comment]
alright, i fixed the other four things - take a look and let me know.

also, I will edit my first post to give brief overview of what has been done and what still needs to be done.

**Comment by Tazinho** [comment]
So from my side your edits are fine.

I was only confused about your change of "tracemem(1:10)" to "r tracemem(1:10)" within the 

Why is tracemem(1:10) not useful? - exercise. And changed it again...

For the rest. Yes I think it would be nice if you read it once (it's optional) and afterwards we close here.

**Comment by Tazinho** [comment]
Ah and BTW. We should talk about the reviewing process, which I summarised above ASAP.

**Comment by henningsway** [comment]
reopend because of: https://github.com/hadley/adv-r/issues/1324

**Comment by henningsway** [comment]
(bin dran)

**Comment by Tazinho** [comment]
Let's wait for this issue (again): https://github.com/hadley/adv-r/issues/1324
Afterwards, pls review the final exercise. (I edited the starting post again).

Then we can close here :)

**Comment by Tazinho** [comment]
The indenting for Prerequisites and the object size prediction needs to be corrected again.

**Comment by henningsway** [comment]
@Tazinho this is strange, when I look at the code, the indentation (3 spaces prose, 4 spaces code) looks fine. But when I knit it, it turns out incorrectly.

It may have sth to do with my new machine (??). Could you take a look on your machine?

**Comment by Tazinho** [comment]
In the exercise part was a line beginning with 2 spaces instead of 3.

For the prerequisites part I have no idea.
