### ISSUE TITLE
[Review] - "7. Environments"-Chapter

### ISSUE THREAD

**Issue by Tazinho** [Tazinho/Advanced-R-Solutions#96]
### [Environment basics](https://advanced-r-solutions.rbind.io/environments.html#environment-basics)

- [ ] 1. List three ways in which an environment differs from a list...
- [ ] 2. Create an environment as illustrated by this picture...
- [ ] 3. Create a pair of environments as illustrated by this picture...
- [ ] 4. Explain why e[[1]] and e[c("a", "b")] don’t make sense when...
- [ ] 5. Create a version of env_poke() that will only bind new names, never...

### [Recursing over environments](https://advanced-r-solutions.rbind.io/environments.html#recursing-over-environments)

- [ ] 1. Modify where() to return all environments that contain a binding for...
- [ ] 2. Write a function called fget() that finds only function objects. It...

### [Special environments](https://advanced-r-solutions.rbind.io/environments.html#special-environments)

- [ ] 1. How is search_envs() different fo env_parents(global_env())...
- [ ] 2. Draw a diagram that shows the enclosing environments of this...
- [ ] 3. Write an enhanced version of str() that provides more information...

### [The call stack](https://advanced-r-solutions.rbind.io/environments.html#the-call-stack)

- [ ] 1. Write a function that lists all the variables defined in the environment...

### [<<-](https://advanced-r-solutions.rbind.io/environments.html#<<-)

- [ ] 1. What does this function do? How does it differ from <<- and why...

**Comment by dongzhuoer** [comment]
Environment basics get [6th question](https://adv-r.hadley.nz/environments.html#exercises-18)

> What does this function do? How does it differ from <<- and why might you prefer it?

`rebind()` basically does the similar thing as `<<-` saved for the following difference.

There are two major difference:
 -  `<<-` starts from the parent environment, but `rebind()` from the current environment
 - when the given name can't be find, `rebind()` throw an error while `<<-` create a new variable 

The second difference makes `rebind()` desirable since it won't contaminate the global environment.

**Comment by dongzhuoer** [comment]
Later I found that the answer exist in [7.5 <<-](https://advanced-r-solutions.rbind.io/environments.html#section). Anyhow, my answer may serve as a supplementary.
